name: CI

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust toolchain
      run: |
        rustup set profile minimal
        rustup toolchain install nightly-2020-06-04 --component rustfmt --component clippy
        rustup override set nightly-2020-06-04
    - name: Check code format
      run: cd kernel && cargo fmt -- --check

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13]
        # we will bring back mipsel later
        arch: [x86_64, riscv32, riscv64, aarch64, mipsel]
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Install Rust toolchain
      run: |
        rustup set profile minimal
        rustup toolchain install nightly-2020-06-04 --component rust-src --component llvm-tools-preview
        rustup override set nightly-2020-06-04

    - name: Install dependencies
      if: runner.os == 'Linux'
      run: sudo apt install -y device-tree-compiler
    - name: Install dependencies
      if: runner.os == 'macOS'
      run: brew install dtc

    - name: Install QEMU
      if: runner.os == 'Linux'
      run: |
        case "${{ matrix.arch }}" in
          x86_64)           PKG=qemu-system-x86 ;;
          riscv32|riscv64)  PKG=qemu-system-riscv ;;
          aarch64)          PKG=qemu-system-arm ;;
          mipsel)           PKG=qemu-system-mips ;;
        esac
        sudo apt install -y $PKG
    - name: Install QEMU
      if: runner.os == 'macOS'
      run: brew install qemu

    - name: Download prebuilt user image
      run: cd user && make sfsimg ARCH=${{ matrix.arch }} PREBUILT=1 && cd ..

    - name: Build kernel
      run: cd kernel && make build ARCH=${{ matrix.arch }} && cd ..
    - name: Build kernel with hypervisor
      if: runner.os == 'Linux' && matrix.arch == 'x86_64'
      run: cd kernel && make build ARCH=${{ matrix.arch }} HYPERVISOR=on && cd ..
